/**
 * Baum - OpenAPI 2.0
 * Baum API by Pcampus Studio (studio.pcampus.net)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pcampus.network@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Materials } from './materials';
import { Topics } from './topics';


export interface Course { 
    name?: string;
    slug?: string;
    price?: number;
    createdDate?: Date;
    /**
     * คำโปรย
     */
    caption?: string;
    /**
     * เนื้อหาหลัก
     */
    details?: string;
    /**
     * Learning topics
     */
    topics?: Array<Topics>;
    /**
     * รายละเอียดเนื้อหาโดยย่อเป็นข้อๆ
     */
    content?: Array<string>;
    /**
     * โฆษณา รายละเอียด
     */
    expression?: Array<string>;
    /**
     * ผู้อบรม
     */
    instructor?: string;
    /**
     * Learning materials
     */
    materials?: Array<Materials>;
    images?: Array<string>;
    /**
     * Course status
     */
    status?: Course.StatusEnum;
}
export namespace Course {
    export type StatusEnum = 'Enable' | 'Disable';
    export const StatusEnum = {
        Enable: 'Enable' as StatusEnum,
        Disable: 'Disable' as StatusEnum
    };
}
