/**
 * Baum - OpenAPI 2.0
 * Baum API by Pcampus Studio (studio.pcampus.net)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pcampus.network@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Page } from './page';


export interface Homepage { 
    home?: Array<Page>;
    aboutUs?: Array<Page>;
    training?: Array<Page>;
    services?: Array<Page>;
    projects?: Array<Page>;
    news?: Array<Page>;
    publications?: Array<Page>;
}
