/**
 * Baum - OpenAPI 2.0
 * Baum API by Pcampus Studio (studio.pcampus.net)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pcampus.network@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Questions } from './questions';


export interface Order { 
    trainingId?: string;
    courseId?: string;
    quantity?: number;
    /**
     * Material id
     */
    material?: string;
    shipDate?: Date;
    /**
     * Order Status
     */
    status?: Order.StatusEnum;
    /**
     * จากบัญชี หรือ ไม่เป็นสมาชิกสามารถกรอกใหม่
     */
    address?: string;
    /**
     * เลือกว่าเป็น online ? onsite ?
     */
    type?: string;
    complete?: boolean;
    price?: number;
    noted?: string;
    ownId?: string;
    questions?: Array<Questions>;
    agree?: boolean;
}
export namespace Order {
    export type StatusEnum = 'placed' | 'approved' | 'delivered';
    export const StatusEnum = {
        Placed: 'placed' as StatusEnum,
        Approved: 'approved' as StatusEnum,
        Delivered: 'delivered' as StatusEnum
    };
}
