/**
 * Baum - OpenAPI 2.0
 * Baum API by Pcampus Studio (studio.pcampus.net)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pcampus.network@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Topics { 
    number?: number;
    title?: string;
    description?: string;
    pictures?: Array<string>;
    videos?: Array<string>;
    urls?: Array<string>;
    files?: Array<string>;
    speakers?: Array<string>;
}
