/**
 * Baum - OpenAPI 2.0
 * Baum API by Pcampus Studio (studio.pcampus.net)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: pcampus.network@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Training { 
    courseId?: string;
    title?: string;
    createdDate?: Date;
    startDate?: Date;
    slug?: string;
    /**
     * จำนวนวันที่อบรม
     */
    days?: number;
    /**
     * จำนวนคนที่เข้าร่วมอบรม
     */
    limit?: number;
    /**
     * Course type
     */
    type?: Training.TypeEnum;
    /**
     * สถานที่จัดอบรม
     */
    place?: string;
    price?: string;
    caption?: string;
    details?: string;
}
export namespace Training {
    export type TypeEnum = 'Online' | 'Onsite';
    export const TypeEnum = {
        Online: 'Online' as TypeEnum,
        Onsite: 'Onsite' as TypeEnum
    };
}
