export * from './auth.service';
import { AuthService } from './auth.service';
export * from './course.service';
import { CourseService } from './course.service';
export * from './instructor.service';
import { InstructorService } from './instructor.service';
export * from './material.service';
import { MaterialService } from './material.service';
export * from './news.service';
import { NewsService } from './news.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './pages.service';
import { PagesService } from './pages.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './publication.service';
import { PublicationService } from './publication.service';
export * from './review.service';
import { ReviewService } from './review.service';
export * from './service.service';
import { ServiceService } from './service.service';
export * from './shares.service';
import { SharesService } from './shares.service';
export * from './training.service';
import { TrainingService } from './training.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AuthService, CourseService, InstructorService, MaterialService, NewsService, OrderService, PagesService, ProjectService, PublicationService, ReviewService, ServiceService, SharesService, TrainingService, UserService];
